source: COMPASS_POSTGRES
target: SNOWFLAKE


streams:
  public.analytics:
    mode: incremental
    primary_key: 'id'
    object: 'sling.compass.analytics'
  
  public.bot_to_connections:
    mode: incremental
    primary_key: 'id'
    update_key: 'updated_at'
    object: 'sling.compass.bot_to_connections'
  
  public.connections:
    mode: incremental
    primary_key: 'id'
    update_key: 'updated_at'
    object: 'sling.compass.connections'
  
  public.organizations:
    mode: incremental
    primary_key: 'organization_id'
    object: 'sling.compass.organizations'
  
  public.plan_limits:
    mode: incremental
    primary_key: 'id'
    update_key: 'updated_at'
    object: 'sling.compass.plan_limits'
  
  public.usage_tracking:
    mode: incremental
    primary_key: 'id'
    update_key: 'updated_at'
    object: 'sling.compass.usage_tracking'

  public.referral_tokens:
    mode: incremental
    primary_key: 'id'
    update_key: 'created_at'
    object: 'sling.compass.referral_tokens'

  public.org_users:
    mode: incremental
    primary_key: 'id'
    update_key: 'created_at'
    object: 'sling.compass.org_users'

  public.org_channels:
    mode: incremental
    primary_key: 'id'
    update_key: 'created_at'
    object: 'sling.compass.org_channels'
  
  public.bot_instances:
    mode: incremental
    primary_key: 'id'
    update_key: 'updated_at'
    object: 'sling.compass.bot_instances'