source: COMPASS_STAGING_POSTGRES
target: SNOWFLAKE


streams:
  public.analytics:
    mode: incremental
    primary_key: 'id'
    object: 'sling.compass_staging.analytics'
  
  public.bot_to_connections:
    mode: incremental
    primary_key: 'id'
    update_key: 'updated_at'
    object: 'sling.compass_staging.bot_to_connections'
  
  public.connections:
    mode: incremental
    primary_key: 'id'
    update_key: 'updated_at'
    object: 'sling.compass_staging.connections'
  
  public.organizations:
    mode: incremental
    primary_key: 'organization_id'
    object: 'sling.compass_staging.organizations'
  
  public.plan_limits:
    mode: incremental
    primary_key: 'id'
    update_key: 'updated_at'
    object: 'sling.compass_staging.plan_limits'
  
  public.usage_tracking:
    mode: incremental
    primary_key: 'id'
    update_key: 'updated_at'
    object: 'sling.compass_staging.usage_tracking'

  public.referral_tokens:
    mode: incremental
    primary_key: 'id'
    update_key: 'created_at'
    object: 'sling.compass_staging.referral_tokens'

  public.org_channels:
    mode: incremental
    primary_key: 'id'
    update_key: 'created_at'
    object: 'sling.compass_staging.org_channels'
  
  public.bot_instances:
    mode: incremental
    primary_key: 'id'
    update_key: 'updated_at'
    object: 'sling.compass_staging.bot_instances'