source: PURINA_CLOUD_REPORTING
target: REPORTING_DB
defaults: 
  mode: full-refresh
  object: '{stream_table}'
  primary_key: [organization_id]

streams: 
  
  purina.mart_sales.reporting_contract_info:
    object: reporting_contract_info
    meta:
      dagster:
        asset_key: public.salesforce_contract_info